Klimabevaegelsen/landbruget.dk

backend/Dockerfile.sync
backend/sync_app.py

- Move base.py to correct location
- Add __init__.py files for proper Python packaging
- Rename main.py to sync_app.py
- Add proper logging to sync service
- Clean up import paths

Fix project structure and imports:

---

backend/.dockerignore
backend/Dockerfile.sync
backend/cloudbuild.yaml
backend/src/base.py

- Add multi-stage Docker build
- Enable Docker layer caching
- Add .dockerignore
- Add clean_value function to base.py

Optimize build and fix clean_value import:

---

backend/src/sources/parsers/cadastral.py

- Add proper cleanup in fetch_chunk
- Improve logging for Cloud Run
- Remove tqdm progress bars
- Add better error handling
- Keep all core functionality intact

fix: optimize cadastral sync for Cloud Run environment

---

backend/scripts/sync_cadastral.py

- Use parallel streaming implementation for better performance
- Process and sync data concurrently
- Reduce memory usage
- Improve Cloud Run compatibility

feat: switch to parallel streaming sync

---

backend/src/sources/parsers/cadastral.py

- Remove tqdm progress bars (not needed in Cloud Run)
- Clean up duplicate logging setup
- Ensure proper resource cleanup
- Improve logging format for Cloud Run environment

fix: optimize cloud run sync process

---

backend/scripts/sync_cadastral.py
backend/src/base.py
backend/src/sources/parsers/cadastral.py
backend/sync_app.py

- Add debug logging in base.py for clean_value function
- Add debug logging in sync_cadastral.py
- Improve logging format in sync_app.py
- Add detailed debug logging in cadastral.py for type tracking

fix: add comprehensive debug logging

---

backend/src/sources/parsers/cadastral.py

- Add explicit string handling for latest_case_id in _parse_feature
- Remove excessive per-row logging
- Fix query definition in _batch_insert
- Only log every 10,000 records for better performance

fix: ensure latest_case_id stays as string and clean up logging

---

backend/scripts/sync_cadastral.py
backend/src/base.py
backend/sync_app.py

- Remove debug level logging
- Set all loggers to INFO level
- Remove unnecessary logging statements
- Keep only essential progress logs

fix: reduce excessive logging

---

backend/scripts/sync_cadastral.py
backend/src/base.py
backend/src/sources/parsers/cadastral.py
backend/sync_app.py

- Add streaming implementation with controlled memory usage
- Implement producer-consumer pattern with queues
- Add parallel processing with fetch, process, and db workers
- Add type hints to base Source class
- Improve error logging and handling
- Add better success/failure reporting

feat: implement streaming for cadastral sync

---

backend/src/sources/parsers/cadastral.py

- Add datetime parsing for registration_from and effect_from fields
- Add proper error handling for datetime parsing
- Add logging for parsing failures

fix: convert timestamp strings to datetime objects

---

backend/src/sources/parsers/cadastral.py

- Add NaN handling for all fields
- Add clean_field helper function
- Convert NaN to None for database insertion

fix: handle NaN values in cadastral data

---

backend/src/sources/parsers/cadastral.py

- Add tracking of processed chunks
- Add duplicate chunk detection
- Add better logging of chunk processing
- Add verification of processed chunks
- Include chunk indices in queue items

fix: add chunk tracking to prevent data loss

---

backend/src/sources/parsers/cadastral.py

- Add explicit transaction commits
- Add batch numbering for better tracking
- Add final count verification
- Improve error logging for batches

fix: improve transaction handling and verification

---

backend/src/sources/parsers/cadastral.py

- Remove async with transaction context
- Add explicit transaction start/commit/rollback
- Remove redundant COMMIT command
- Add proper error handling for transactions

fix: proper transaction handling

---

backend/src/sources/parsers/cadastral.py

- Add explicit transaction handling
- Add condition to only update newer records
- Add sample record verification
- Improve error handling and logging
- Fix issue with records not accumulating properly

fix: improve batch insert handling

---

backend/src/config.py
backend/src/sources/parsers/cadastral.py

- Update endpoint to wfs.datafordeler.dk
- Update WFS namespaces for 2.0.0
- Fix parameter names to match WFS 2.0.0 spec
- Improve feature count handling for WFS 2.0.0
- Update XML parsing for WFS 2.0.0 responses

Update WFS endpoint and improve WFS 2.0.0 compatibility

---

backend/src/sources/parsers/cadastral.py

- Add detailed logging for parameter creation
- Log start_index, max_features, and page_size values
- Help track down None value error in WFS requests

Add debug logging for WFS parameters

---

backend/src/sources/parsers/cadastral.py

- Add geometry validation in _parse_feature
- Add robust geometry handling in _prepare_records
- Better error logging for invalid geometries
- Attempt to fix invalid geometries with buffer(0)

Improve geometry handling in cadastral parser

---

backend/src/sources/parsers/cadastral.py

- Add detailed logging in _parse_geometry
- Track BFE numbers throughout geometry processing
- Log coordinate parsing and validation steps
- Add geometry statistics in batch processing
- Improve error messages for debugging in Cloud Run

Add comprehensive geometry logging

---

backend/src/sources/parsers/cadastral.py

- Adjust timeouts for large dataset (5min per request, 2h total)
- Improve pagination handling for 2M+ records
- Add better progress tracking and logging
- Implement retry logic with exponential backoff
- Add memory usage monitoring

Optimize Cadastral sync with better timeouts and pagination handling

---

backend/src/sources/parsers/cadastral.py

- Split parameters into base and pagination
- Remove count parameter from total count request
- Now correctly shows total of 2,152,200 features

Fix cadastral total count to handle full 2.1M+ features

---

backend/src/sources/parsers/cadastral.py

- Update _get_total_count to use exact working parameters
- Update _fetch_chunk to match test script approach
- Remove unused parameter helper methods
- Simplify error handling and logging
- Should now correctly handle all 2.1M+ features

Fix cadastral pagination to match working test script

---

backend/scripts/sync_wetlands.py
backend/src/config.py
backend/src/sources/parsers/wetlands.py

- Add wetlands parser for WFS data
- Add wetlands sync script
- Update config with wetlands source

Add wetlands sync parser and script

---

backend/src/sources/parsers/wetlands.py

- Remove geopandas dependency
- Follow cadastral parser pattern for geometry handling
- Simplify geometry processing

Update wetlands parser to use shapely directly

---

backend/src/sources/parsers/wetlands.py

- Add total_timeout_config
- Match cadastral parser timeout setup

Fix timeout configuration in wetlands parser

---

backend/src/sources/parsers/water_projects.py

- Add detailed progress logging for each layer
- Add request/response debugging information
- Add feature parsing logs
- Add performance metrics
- Add error details and stack traces

feat: add comprehensive logging to water projects parser

---

backend/scripts/sync_water_projects.py
backend/src/config.py
backend/src/sources/parsers/water_projects.py

- Add support for kla_projektforslag and kla_projektomraader layers
- Handle wkb_geometry field name variation
- Add URL mapping for MIM endpoint
- Update database schema with new fields
- Update area field handling

feat: add KLA water project layers from MIM endpoint

---

backend/src/config.py
backend/src/sources/parsers/water_projects.py

- Add water_projects_combined table
- Add configuration options for combined layer creation
- Add ST_Union operation to merge all water project geometries
- Add error handling and timeout for union operation

Add combined layer functionality to water projects

---

backend/src/sources/parsers/water_projects.py

- Add logging for feature parsing process
- Add logging for batch insert operations
- Add table count check at sync start
- Add geometry validation logging
- Add transaction logging

Add detailed logging for water projects sync

---

backend/src/sources/parsers/water_projects.py

- Update _parse_geometry method to handle MultiSurface elements correctly
- Add support for both single Polygon and MultiPolygon geometries
- Improve error handling and logging
- Fix namespace handling for GML elements
- Verified working with all layer types through tests

fix: improve geometry parsing in water projects parser

---

backend/requirements.txt
backend/src/base.py
backend/src/config.py
backend/src/sources/parsers/cadastral.py
backend/src/sources/parsers/water_projects.py
backend/src/sources/parsers/wetlands.py

- Replace PostgreSQL storage with GeoParquet format
- Implement Cloud Storage integration for all parsers
- Update base Source class with storage utilities
- Add GeoParquet dependencies and GDAL support
- Maintain consistent storage path structure
Parsers affected:
- Cadastral
- Wetlands
- Water Projects

Migrate parsers to GeoParquet and Cloud Storage

---

backend/Dockerfile.processing
dags/data_processing.py

- Add Dataflow container with geospatial support
- Update DAG to use custom container
- Configure geometry validation pipeline

feat: add Dataflow processing pipeline

---

.github/workflows/deploy-sync-jobs.yml
dags/data_processing.py

- Add dataflow-processing to deployment workflow
- Skip Cloud Run job creation for processing container
- Update DAG to use correct container name

fix: setup dataflow processing container and update DAG to use it

---

dags/data_processing.py

- Add setup_file and requirements_file to Dataflow options
- Use container dependencies for Python packages

fix: add setup and requirements files to Dataflow job

---

backend/dataflow/validate_geometries.py

- Move imports inside worker functions
- Separate read/write operations
- Pass bucket names explicitly
- Follow Apache Beam best practices

fix: refactor dataflow script for worker imports

---

backend/Dockerfile.processing

- Remove fixed ENTRYPOINT from container
- Allow Dataflow to control worker initialization
- Follow Apache Beam best practices for custom containers

fix: remove container entrypoint for Dataflow compatibility

---

backend/Dockerfile.processing

- Set Beam version to 2.60.0 to match submission environment
- Remove ENTRYPOINT to allow Dataflow control
- Fix container compatibility issues

fix: match Beam versions between environments

---

backend/dataflow/validate_geometries.py

- Add proper function definitions
- Fix value provider access with .get()
- Ensure correct scoping of functions

fix: correct Dataflow script issues

---

backend/dataflow/validate_geometries.py

- Remove incorrect value provider .get() calls
- Fix string argument handling
- Match DataflowCreatePythonJobOperator expectations

fix: remove .get() calls from options

---

.github/workflows/deploy-sync-jobs.yml
backend/scripts/sync_agricultural_fields.py
backend/src/sources/parsers/agricultural_fields.py
backend/sync_app.py

- Add agricultural fields parser with optimized batch processing
- Add sync script for agricultural fields
- Update sync app to include agricultural fields
- Add agricultural fields sync job to GitHub workflow

feat: add agricultural fields sync

---

backend/src/config.py
backend/src/sources/parsers/water_projects.py

- Add support for ArcGIS REST services in WaterProjects class
- Add new NST layer for climate lowland projects
- Update config with NST URL
- Maintain consistent data structure across sources

feat: add NST climate lowland projects via ArcGIS REST API

---

.github/workflows/deploy-sync-jobs.yml

- Run data-sync and dataflow-processing builds concurrently
- Add proper error handling for parallel builds
- Expected ~40% reduction in build time

perf: parallelize container builds in GitHub Actions workflow

---

.github/workflows/deploy-sync-jobs.yml
backend/src/config.py
backend/src/sources/parsers/water_projects.py
backend/src/sources/parsers/wetlands.py

- Add dissolved geometry creation to wetlands and water projects
- Store dissolved geometries alongside regular parquet files
- Update Cloud Run job configurations for memory and timeout
- Remove unused dataflow processing job

Add geometry dissolution to wetlands and water projects parsers

---

backend/src/sources/parsers/cadastral.py

- Fix coordinate parsing in geometry handling
- Add better validation and error logging
- Improve sync process with cloud-friendly progress tracking
- Add backoff retry for storage operations
- Remove tqdm dependency for Cloud Run compatibility

fix(cadastral): Improve feature parsing and error handling

---

backend/Dockerfile.sync
backend/requirements.txt
backend/src/sources/parsers/wetlands.py

- Add dask and dask-geopandas dependencies
- Implement parallel geometry dissolution using Dask
- Add detailed performance logging
- Update Dockerfile.sync with Dask dependencies

Add Dask parallel processing for wetlands dissolution

---

.github/workflows/deploy-sync-jobs.yml
backend/src/sources/parsers/wetlands.py

- Increase wetlands sync job memory to 16GB
- Add cleanup of working files at start of sync
- Ensure clean state for each run

Optimize wetlands processing

---

backend/requirements.txt

- Use gridcode for two-step dissolution process
- Remove Dask dependencies (no longer needed)
- Add detailed progress logging
- Clean up working files at start

Optimize wetlands dissolution using gridcode

---

backend/src/sources/parsers/wetlands.py

- Replace linemerge with unary_union for boundaries
- Handle shared edges between grid cells automatically
- Improve performance with direct boundary union
- Add detailed timing logs for each step
- Keep operations in original CRS until final transform

Optimize grid cell boundary merging

---

backend/src/sources/parsers/wetlands.py

- Remove final unary_union to keep polygons separate
- Add wetland_id for tracking individual features
- Keep polygons dissolved where they touch but separate otherwise
- Optimize for BigQuery spatial operations
- Update logging to show number of features

Keep dissolved wetland polygons separate

---

backend/src/sources/parsers/wetlands.py

- Fix understanding: features are adjacent, not overlapping
- Use boundaries to find where features touch
- Merge features only where they share boundaries
- Keep features separate where they don't touch
- Update logging to reflect correct process

Fix wetlands merge for adjacent features

---

backend/src/sources/parsers/wetlands.py

- Add geometry analysis and statistics logging
- Optimize dissolve operation for grid-aligned cells
- Add pre and post-dissolve statistics reporting
- Remove unnecessary geometry snapping since source is grid-aligned

feat(wetlands): improve geometry merging and add detailed statistics

---

backend/src/sources/parsers/wetlands.py

- Replace dissolve with edge-based merging algorithm
- Add area validation and detailed logging
- Preserve grid alignment
- More memory efficient approach using edge matching
- Add polygon reconstruction from boundary edges

feat(wetlands): implement efficient edge-based polygon merging

---

backend/src/sources/parsers/water_projects.py

- Keep geometric operations in EPSG:25832
- Use validator for initial validation but maintain 25832 for dissolve
- Single final conversion to WGS84 before storage
- Add detailed logging of CRS transformations

fix: improve CRS handling in water projects dissolve

---

backend/src/sources/parsers/water_projects.py

- Remove redundant dissolve operation
- Keep single dissolve with proper CRS handling
- Fix issue where second dissolve was shrinking geometry bounds
- Add more detailed logging of dissolve process

fix: remove double dissolve operation

---

backend/src/sources/parsers/water_projects.py

- Remove redundant dissolve operation
- Add validation before final save
- Keep single dissolve at sync completion
- Maintain proper CRS handling throughout

fix: improve water projects dissolve process

---

backend/src/sources/utils/geometry_validator.py

- Add orient() to fix polygon ring orientation
- Ensure exterior rings are counter-clockwise
- Ensure interior rings are clockwise
- Apply orientation fix to all polygon geometries
- Keep existing validation functionality

fix: ensure proper geometry orientation for BigQuery

---

backend/src/sources/parsers/water_projects.py

- Remove redundant conversion to WGS84 before storage
- Geometries are already in EPSG:4326 after dissolve and cleaning
- Maintains proper CRS handling throughout the pipeline

fix: Remove duplicate CRS conversion in water projects

---

backend/src/sources/parsers/water_projects.py
backend/src/sources/utils/geometry_validator.py

- Clean geometries before and after dissolve operation
- Improve CRS transformation handling in validator
- Fix issues with overlapping polygons
- Maintain proper geometry validity throughout the pipeline

fix: Improve geometry cleaning in water projects

---

backend/src/sources/parsers/water_projects.py

- Transform to WGS84 before dissolve operation
- Ensure all geometric operations happen in BigQuery's CRS
- Add strict validation to catch invalid geometries
- Fail fast if BigQuery requirements aren't met

fix: Dissolve water projects in WGS84

---

backend/src/sources/parsers/water_projects.py

- Keep all geometry operations in UTM until final conversion
- Clean geometries before and after dissolve
- Handle transformation overlaps with unary_union
- Add strict BigQuery validity check before storage
- Fail fast if geometries don't meet BigQuery requirements

fix: Add final BigQuery validity check for water projects

---

backend/src/sources/parsers/water_projects.py

- Log validity status for each invalid geometry
- Check and log ring orientations
- Check and log duplicate vertices
- Show exact reason why geometries fail BigQuery validation

debug: Add detailed logging for invalid geometries

---

backend/src/sources/parsers/water_projects.py
backend/src/sources/utils/geometry_validator.py

- Combine validation functions into one thorough implementation
- Work in UTM for better precision with Danish data
- Add comprehensive validation and cleanup steps
- Improve logging and error handling

fix: consolidate geometry validation into single robust function

---

backend/src/sources/parsers/water_projects.py
backend/src/sources/utils/geometry_validator.py

- Add detailed geometry inspection after dissolve
- Log coordinates of invalid geometries
- Track validity and simplicity at each step
- Remove redundant BigQuery validation
- Streamline validation process

feat: improve geometry validation logging

---

backend/src/sources/parsers/water_projects.py

- Add proper polygon orientation in UTM
- Add small buffer operations to clean artifacts
- Add UTM validation before WGS84 conversion
- Simplify cleanup process to maintain precision

fix: enhance geometry cleanup in UTM

---

.github/workflows/deploy-sync-jobs.yml
backend/scripts/sync_property_owners.py
backend/src/config.py
backend/src/sources/parsers/__init__.py
backend/src/sources/parsers/property_owners.py

- Add PropertyOwnersParser for handling SFTP downloads
- Add sync script for Cloud Run job
- Move sensitive credentials to Secret Manager
- Add Cloud Run sync job configuration

Add property owners sync from Datafordeler SFTP

---

backend/src/sources/static/pesticides/README.md
backend/src/sources/static/pesticides/parser.py

fixes #12 (done by @aleksanderbl29 )

Restore pesticide data from aleksanderbl29's contribution

---

.github/workflows/bmd_monthly.yml
.gitignore
backend/pipelines/bmd_scraper/.env.example
backend/pipelines/bmd_scraper/Dockerfile
backend/pipelines/bmd_scraper/README.md
backend/pipelines/bmd_scraper/bronze/__init__.py
backend/pipelines/bmd_scraper/bronze/export.py
backend/pipelines/bmd_scraper/docker-compose.yml
backend/pipelines/bmd_scraper/main.py
backend/pipelines/bmd_scraper/pyproject.toml
backend/pipelines/bmd_scraper/requirements.txt
backend/pipelines/bmd_scraper/silver/__init__.py
backend/pipelines/bmd_scraper/silver/transform.py

implementation for this issue #15

feat: init bmd pipeline

---

backend/api/supabase/functions/api/config.yaml
backend/api/supabase/functions/api/index.ts

Refactor: Standardize DataGrid component type and properties

---

backend/api/supabase/functions/api/index.ts

This PR introduces more specific logging for debugging performance issues, particularly around the getLatestYearForCompany function and site_species_production_ranked. It also comments out some verbose logging in processDataGrid.

Chore: Add detailed logging for performance analysis

---

backend/api/supabase/functions/api/config.yaml
backend/api/supabase/functions/api/index.ts

This PR removes all references to isCollapsible from the backend API and config files. fixes #308.

fix: remove isCollapsible from API and config

---

backend/pipelines/unified_pipeline/src/tests/bronze/test_agricultural_fields.py
backend/pipelines/unified_pipeline/src/tests/bronze/test_bnbo_status.py
backend/pipelines/unified_pipeline/src/tests/silver/test_agricultural_fields.py
backend/pipelines/unified_pipeline/src/tests/silver/test_bnbo_status.py
backend/pipelines/unified_pipeline/src/unified_pipeline/app.py
backend/pipelines/unified_pipeline/src/unified_pipeline/bronze/agricultural_fields.py
backend/pipelines/unified_pipeline/src/unified_pipeline/bronze/bnbo_status.py
backend/pipelines/unified_pipeline/src/unified_pipeline/common/base.py
backend/pipelines/unified_pipeline/src/unified_pipeline/model/cli.py
backend/pipelines/unified_pipeline/src/unified_pipeline/silver/agricultural_fields.py
backend/pipelines/unified_pipeline/src/unified_pipeline/silver/bnbo_status.py
backend/pipelines/unified_pipeline/src/unified_pipeline/util/timing.py

Agricultural fields jobs for bronze and silver stage.

---

frontend/src/components/chart/custom-legend.tsx
frontend/src/components/pagebuilder/pageBlocks/block-bar-chart.tsx
frontend/src/components/pagebuilder/pageBlocks/block-combo-chart.tsx
frontend/src/components/pagebuilder/pageBlocks/block-info-card.tsx
frontend/src/components/pagebuilder/pageBlocks/block-kpi-group.tsx
frontend/src/components/pagebuilder/pagebuilder.tsx
frontend/src/components/table/data-table-pagination.tsx

Implementation of combochart. Tweaks to several other viz components

306 frontend   build all viz components from company data output

---

.github/workflows/unified_pipeline.yml

update python version

---

backend/api/supabase/functions/api/index.ts
backend/api/supabase/migrations/20250523223537_add_complex_iterated_test_data.sql
frontend/src/services/supabase/types.ts

Here's the PR description you can fill out:
Fixes #321  
The missing `_key` field was causing routing uniqueness issues in the frontend when rendering nested iteratedSections. Each section now gets a programmatically generated unique key that can be used for React component keys and routing.
1. **Test API Response Structure**:
```bash
curl "https://your-api-url/api?id=a1a1a1a1-0001-0001-0001-a1a1a1a1a1a1"
```
2. **Verify _key Fields**:
- Check that each object in `pageBuilder[].sections[]` now has a `_key` field
- Verify keys follow the pattern: `{parentKey}-item-{index}` (e.g., `animal-welfare-sites-iteration-item-0`)
- Ensure all keys are unique within the same iteratedSection
3. **Test Frontend Rendering**:
- Navigate to a company page with iteratedSections 
- Verify that collapsible …

fix: Add missing _key field to IteratedSections - closes #321

---

backend/pipelines/unified_pipeline/pyproject.toml
backend/pipelines/unified_pipeline/src/tests/bronze/test_agricultural_fields.py
backend/pipelines/unified_pipeline/src/tests/bronze/test_bnbo_status.py
backend/pipelines/unified_pipeline/src/tests/bronze/test_water_projects.py
backend/pipelines/unified_pipeline/src/tests/bronze/test_wetlands.py
backend/pipelines/unified_pipeline/src/tests/common/__init__.py
backend/pipelines/unified_pipeline/src/tests/common/test_base.py
backend/pipelines/unified_pipeline/src/tests/silver/test_bnbo_status.py
backend/pipelines/unified_pipeline/src/tests/silver/test_water_projects.py
backend/pipelines/unified_pipeline/src/tests/silver/test_wetlands.py
backend/pipelines/unified_pipeline/src/unified_pipeline/app.py
backend/pipelines/unified_pipeline/src/unified_pipeline/bronze/agricultural_fields.py
backend/pipelines/unified_pipeline/src/unified_pipeline/bronze/bnbo_status.py
backend/pipelines/unified_pipeline/src/unified_pipeline/bronze/water_projects.py
backend/pipelines/unified_pipeline/src/unified_pipeline/bronze/wetlands.py
backend/pipelines/unified_pipeline/src/unified_pipeline/common/base.py
backend/pipelines/unified_pipeline/src/unified_pipeline/model/cli.py
backend/pipelines/unified_pipeline/src/unified_pipeline/silver/bnbo_status.py
backend/pipelines/unified_pipeline/src/unified_pipeline/silver/water_projects.py
backend/pipelines/unified_pipeline/src/unified_pipeline/silver/wetlands.py

Last 2 remaining jobs in this issue.
Fixes #252

feat: Added wetlands bronze and silver jobs.

---

.gitignore
backend/README.md
backend/pipelines/README.md

Adds comprehensive documentation for using act to test GitHub Actions workflows locally. Includes installation guide, usage examples, security considerations, and updates .gitignore for test credentials.

docs: Add local GitHub Actions testing with act

---

.github/workflows/unified_pipeline.yml
backend/pipelines/drive_data_pipeline/PERFORMANCE_IMPROVEMENTS.md
backend/pipelines/drive_data_pipeline/bronze/drive/fetcher.py
backend/pipelines/drive_data_pipeline/bronze/metadata.py
backend/pipelines/drive_data_pipeline/bronze/processor.py
backend/pipelines/drive_data_pipeline/main.py
backend/pipelines/drive_data_pipeline/utils/__init__.py
backend/pipelines/drive_data_pipeline/utils/helpers.py
backend/pipelines/unified_pipeline/src/unified_pipeline/bronze/jordbrugsanalyser.py

Performance improvements: eliminate double folder listing (50% API call reduction), fix file path resolution issues, improve download reliability with better retry logic. Expected to reduce runtime from 1+ hours to 20-30 minutes.

Fix: Major performance improvements for drive pipeline

---

backend/pipelines/bbr_buildings/main.py
backend/pipelines/unified_pipeline/src/README_property_cadastral_merge.md
backend/pipelines/unified_pipeline/src/config/property_cadastral_merge_config.json
backend/pipelines/unified_pipeline/src/test_property_cadastral_merge.py
backend/pipelines/unified_pipeline/src/unified_pipeline/silver/property_cadastral_merge.py

Property cadastral bfe merge

---

.github/workflows/chr_pipeline.yml
backend/pipelines/chr_pipeline/main.py
backend/pipelines/drive_data_pipeline/bronze/storage.py
backend/pipelines/drive_data_pipeline/docs/setup.md
backend/pipelines/drive_data_pipeline/docs/user_guide.md
backend/pipelines/drive_data_pipeline/silver/storage.py
backend/pipelines/drive_data_pipeline/utils/helpers.py

CHR Pipeline Fixes:
- Fix bronze file detection logic in main.py to properly check for existing bronze data
- Enhanced logic checks both override directories and default EXPORT_TIMESTAMP directories
- Fixed workflow bronze data download path to match expected directory structure
- Resolves FVM credentials error when bronze data already exists for silver processing
Drive Data Pipeline Fixes:
- Updated storage manager integration components
- Fixed file path handling for both local and GCS storage
- Improved metadata file detection and processing
- Updated documentation
These fixes resolve production issues where pipelines were failing due to:
1. CHR pipeline requiring FVM credentials even when bronze data was available
2. Workflow downloading bronze files to wrong directory structure
3. …

Fix CHR and Drive data pipeline issues
